let owners = {
    ANCHKV: '© СШОР №2 ГБНОУ "СПб ГДТЮ"',
    BBCH_A: '© Бибич Андрей - <a href="https://vk.com/id7840054" target="_blank">ВК</a> или <a href="https://t.me/andy_atta" target="_blank">Telegram</a>.',
    BKTV: 'Все карты <a href="https://t.me/beketov" target="_blank">Константина Бекетова</a> можно свободно использовать в некоммерческих целях.',
    BVZ: '© Татьяна Бевза [<a href="mailto:Tanya-9-8@ya.ru" target="_blank">Tanya-9-8@ya.ru</a>]',
    CHGRVSKY_M: 'По вопросам использования карты обращаться к Михаилу Чегаровскому (+79213300490).',
    CHGRVSKY_V: 'По вопросам использования карты обращаться к Виталию Чегаровскому - vitaly-4@mail.ru.',
    EFRMV: 'По вопросам использования карты - 8-999-086-10-82 (<b>Ефремов Михаил</b>).',
    EGRV_SRG: '© Егоров С.И., kinef-o@mail.ru',
    EGRV_EGR: '© Егоров Е.А.',
    ELTSV: '© Ельцов Денис',
    ELZRV: 'По вопросам использования - Владимир Елизаров orunner1@gmail.com',
    SFSO_SPB: 'Карта принадлежит СФСО СПб. По вопросам использования - info@spbof.ru.',
    GK: '© Горный Кросс, Александр Шумский',
    GOLDMRSHRT: '© Золотой Маршрут - <a href="https://mosplay.ru/" target="_blank">сайт</a> и <a href="https://vk.com/rogaining" target="_blank">ВК</a>',
    GLFSTRM: '© КСО "Гольфстрим"',
    GLTV_YU: '© ГБНОУ "СПб ГДТЮ", Юрий Гультяев - +79213017985, gultiaev@list.ru',
    GUSEV: '© Гусев Илья gusev@ym.spb.ru',
    INGR: '© <a href="https://vk.com/ingriaorient" target="_blank">КСО "Ингрия"</a>, Кирьянов Юрий - 89117954827',
    IMPULS: '© АНО ОПОРА СО СПб и ЛО "Импульс". Контакт для связи: info@impulsnko.ru.',
    ILVES: '© Константин Ильвес - <a href="https://vk.com/sport_for_oll" target="_blank">ВК</a>.',
    KKM: '© <b><a href="https://kkmstart.ru" target="_blank">Кубок Коротких Маршрутов</a></b>, <a href="https://vk.com/id18529372" target="_blank">Сергей Рыжов</a>.',
    KP31: 'Контакты правообладателя: controlpoint31@gmail.com.',
    KOSOR: 'Карта является собственностью ФСО г.Выборг. По вопросам использования карты - +79052770528 (Антон Косоруков).',
    KUZM: 'Карта является собственностью клуба КУЗЬМОЛОВО. По вопросам использования карты - +79213300490 (Михаил Чегаровский).',
    LM: '© Орлов Александр, "Лужский Меридиан".',
    MLV_AL: '© Малов Алексей, leshamalov@yandex.ru',
    MSKV: 'По вопросам использования карты - 8-981-146-94-95 (Москов Игорь).',
    MTRNCHV: 'По вопросам использования карты - Матреничев Вячеслав (iambam@ya.ru).',
    NKLSK: '© Артём Никольский',
    NW: '© Клуб "Nord-West"',
    OPNBND: '© OpenBand - <a href="https://orientband.ru" target="_blank">сайт</a> и <a href="https://vk.com/openband_ru" target="_blank">ВК</a>',
    PARADA: '© Екатерина Новикова (PARADA) - <a href="https://parda.ru/about" target="_blank">сайт</a> и <a href="https://vk.com/parada_ekaterina" target="_blank">ВК</a>',
    RDNV_I: 'Карта доступна свободно для некоммерческого использования. Для получения OCAD-файла и по прочим вопросам обращаться к Ивану Родионову (+7 911 161 6770).',
    RFAR: 'Права на использования карты принадлежат компании Red Fox и оргкомитету соревнований <a href="https://adventure-race.redfox.ru/" target="_blank">Red Fox Adventure Race</a>.',
    SCHLKHN_AN: '© Шелёхин Анатолий',
    SHEIN: 'По вопросам использования карты - 8-921-972-86-24 (<b>Александр Шеин</b>).',
    SHBN: '© Юрий Шубин',
    SHKLV: '© Шкилев В.В. - 8 (921)7473259',
    SHRNN: 'По вопросам использования карты - Александр Альбертович Ширинян, skishar@mail.ru.',
    STRKZK: '© Стрекозайки, 8-911-7546601',
    SVCHK: 'Карта является собственностью КСО "Сертолово". По вопросам использования - 8 921 423 60 46 (Роман Сивачук).',
    TOKM: 'По вопросам использования карты обращайтесь к Константину Токмакову (<a href="mailto:tokma@bk.ru" target="_blank">tokma@bk.ru</a>).',
    VOLKOV_AM: '© Волков А.М.',
    VST_PRZRSK: 'По вопросам использования - клуб <a href="https://vk.com/vesta_priozersk" target="_blank">Веста-Приозерск</a> (И.Скворцова ira-vesta@yandex.ru).',
    WN: 'Права на использования карты принадлежат клубу <b>"Белые Ночи"</b>. По вопросам приобретения и использования карт-материала обращаться к Анне Горбатенковой (89219241742, Телеграмм, WhatsApp).',
    YUVNT: 'По вопросам использования обращаться в ДДТиЭ "Ювента".',
    ZCHNV: '© Зачиняев В.А.',
}