let planners = {
    CHGRVSKY_M: { name: 'Чегаровский Михаил' },
    GBNV_V: { name: 'Губанов Валерий' },
    GRLNV: { name: 'Горланов Сергей' },
    ILVS: { name: 'Ильвес Константин' },
    KSRKV: { name: 'Косоруков Антон' },
    MSLVSKY: { name: 'Масловский Дмитрий' },
    NKTN_I: { name: 'Никитин Иван' },
    PRVSKY: { name: 'Пировский Игорь' },
    PLKV_D: { name: 'Поляков Дмитрий' },
    RYKV_A: { name: 'Райков Александр' },
    SHEIN: { name: 'Шеин Александр' },
    SRBRNTSKY: {name: 'Серебряницкий Константин'},
    TKMKV_K: {name: 'Токмаков Константин' },
    TLNV_A: { name: 'Тюленев Александр' },
    TSVTKV_D: { name: 'Цветков Дмитрий' },
};
