let planners = {
    BDKN_A: { name: 'Будкин А.' },
    CHGRVSKY_M: { name: 'Чегаровский Михаил' },
    CHGRVSKY_V: { name: 'Чегаровский Виталий' },
    DRBSHV: { name: 'Дробышев Сергей' },
    DSHKO: { name: 'Дешко Валерий' },
    EGRV_E: { name: 'Егоров Е' },
    ERMSHKN: { name: 'Ермошкин С' },
    FRSHLVA: { name: 'Фершалова Виктория' },
    GBNV_V: { name: 'Губанов Валерий' },
    GRGRV_B: { name: 'Григорьев Б' },
    GRLNV: { name: 'Горланов Сергей' },
    ILVS: { name: 'Ильвес Константин' },
    KDNV_A: { name: 'Кудинов А' },
    KUOKNN_Y: { name: 'Куокканен Юрий' },
    KSRKV: { name: 'Косоруков Антон' },
    LBDV_S: { name: 'Лебедев С' },
    LVCHV: { name: 'Левичев Александр' },
    MKHLV_V: { name: 'Михайлов В' },
    MLVA_M: { name: 'Малова Мария' },
    MRSKY_S: { name: 'Мурский Сергей' },
    MSLVSKY: { name: 'Масловский Дмитрий' },
    NKLVCH: { name: 'Николаевич А' },
    NKTN_I: { name: 'Никитин Иван' },
    PRVSKY: { name: 'Пировский Игорь' },
    PVLV_M: { name: 'Павлов Михаил' },
    PLKV_D: { name: 'Поляков Дмитрий' },
    RDKV: { name: 'Рудаков Виктор' },
    RYLOV_V: { name: 'Рылов Виктор' },
    RYKV_A: { name: 'Райков Александр' },
    SHEIN: { name: 'Шеин Александр' },
    SHLKV_L: { name: 'Шельков Л' },
    SHRNN: { name: 'Ширинян Александр' },
    SHVR: { name: 'Швер Евгений' },
    SLVVA_L: { name: 'Соловьёва Л' },
    SMNV_M: { name: 'Семёнов Михаил' },
    SRBRNTSKY: {name: 'Серебряницкий Константин'},
    TKMKV_K: {name: 'Токмаков Константин' },
    TLNV_A: { name: 'Тюленев Александр' },
    TSVTKV_D: { name: 'Цветков Дмитрий' },
    TRSV: { name: 'Тарасов Борис' },
    VLKV_A: { name: 'Волков Андрей' },
    VSLVSKY: { name: 'Василевский Александр' }
};
